### ISSUE TITLE
Swift2 branch not working on XCode 7.0

### ISSUE THREAD

**Issue by jlhonora** [tomkowz/Swifternalization#13]
I'm facing issues using Swifternalization on XCode 7 with Cocoapods:

![screen shot 2015-09-22 at 5 11 11 pm](https://cloud.githubusercontent.com/assets/1577721/10030241/12d87c3a-614d-11e5-9f76-6c2d73d77b94.png)

Podfile:

```
pod 'Swifternalization', git: 'https://github.com/tomkowz/Swifternalization.git', branch: 'swift2'
```

Podfile.lock:

```
  Swifternalization:
    :commit: 8ab949ebd260709e23c23792c5cbfe20a10bbc1f
    :git: https://github.com/tomkowz/Swifternalization.git
```

Which corresponds to the latest commit on the swift2 branch. Any hints on getting it to work? Thanks in advance, great lib.

**Comment by tomkowz** [comment]
Yeah, iOS API changed and there should be `advancedBy` and `distanceTo` methods used instead of `advance` and `distance`. You can fix it and send pull request or I'll fix it on Saturday/Sunday
