### ISSUE TITLE
Storyboard + Carthage

### ISSUE THREAD

**Issue by TofPlay** [tomkowz/Swifternalization#17]
Hi
Good component :+1:  Very flexible :smile:  But what's happened for the string under the storyboards?  
Do you have a plan to support [Carthage](https://github.com/Carthage/Carthage)?

**Comment by tomkowz** [comment]
Sorry for the late answer.

Yeah, strings under storyboards will not work. You have to declare everything in the code.

Swifternalization already supports Carthage. Please make sure to use Carthage 0.11.0 or newer when building under Xcode 7.X
