### ISSUE TITLE
Plan for Swift 3 support?

### ISSUE THREAD

**Issue by dumbfingers** [tomkowz/Swifternalization#20]
Hi,

Just wonder if `Swiftnalization` will give any supports for the upcoming Swift 3?

Many thanks

**Comment by tomkowz** [comment]
Hey, not checked whether it works with Swift 3 already, but if not I'll or probably someone add support for it. The only change will be updating syntax.

**Comment by ss1271** [comment]
Cool! Dziękuję 👍

**Comment by tomkowz** [comment]
np. hehe :)
