### ISSUE TITLE
Doesn't parse the label "other" 

### ISSUE THREAD

**Issue by dumbfingers** [tomkowz/Swifternalization#21]
Hi tomkowz

Could you help me with this issue?

Here's the code to reproduce it:

base.json

>     "FollowRequest": {
>         "one": "1 Follow Request",
>         "other": "%d Follow Requests"
>     }

code inside ViewController:

>         let string1 = I18n.localizedString("FollowRequest", intValue: 1)
>         let stringOther = I18n.localizedString("FollowRequest", intValue: 34)
>         print(string1)
>         print(stringOther)

code inside AppDelegate
       
>  I18n.configure(NSBundle.mainBundle())

The print results are as follows:

> 1 Follow Request
> %d Follow Requests

and the results are similar if you have any other language json files. Just the numbers are becoming `%d`

It seems to me that the numbers are not parsed correctly, am I doing something wrong here?

Many thanks

**Comment by tomkowz** [comment]
Hi, sure I can help you.

You're doing everything good, actually. What Swifternalization is doing is just returning you the string proper for value you passed. You passed 1 and you get value matching the "one". You passed 34 and you get value matching the "other". You now are required to pass the value you received (format of string) to string constuctor using String(format:,params). Swifternalization does not put the number inside the value it found. It is up to developer.

So it should look like this:

    let val = 34
    let stringOther = I18n.localizedString("FollowRequest", intValue: val)
    print(String(format: stringOther, val))

**Comment by dumbfingers** [comment]
oh I see, it works now 👍  dzięki
