### ISSUE TITLE
Inequality Expressions not working

### ISSUE THREAD

**Issue by NSCabezon** [tomkowz/Swifternalization#29]
I have on my base.json:

`"post": {
		"ie:x=1": "1 post",
		"ie:x=0": "No posts",
		"ie:x>1": "%d posts"
	}`

then on the code:

`let localizedStr = Swifternalization.localizedString("post", intValue: postCount, fittingWidth: nil, defaultValue: "", comment: nil)`

and I get:

"1 post", "No posts" but I get the literal "%d posts"

**Comment by NSCabezon** [comment]
what am I doing wrong?

**Comment by LongSpaghetti** [comment]
The answer is here
https://github.com/tomkowz/Swifternalization/issues/21
